config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :vendor_categories
  end
  devise_for :customers , :controllers => { :registrations => 'customers_registration' }
  resources :customers

  devise_for :vendor_admins
  namespace :admin do
    resources :users
    resources :products
    resources :colors
    resources :sizes
    resources :orders
    resources :store_settings
    resources :testimonials
    resources :categories
    resources :deal_of_days
    end
  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
   get 'logout' => 'devise/sessions#destroy'
  end

 resources :carts
 resources :orders 
 resources :vendors
 resources :products, only: [:show, :index]
 resources :stores, only: [:show, :index]

 resources :admin, only: [:index]
  match "home/set_session" ,to: "home#change_languages", as: "languagepath", via: [:get]
  match "/newsletter" ,to: "statics#news_subscriber", as: "newssubscriber", via: [:post]
  match "admin/get_color_and_size" ,to: "admin/products#get_size_and_color_of_product", as: "getsizecolor", via: [:get]
  root 'home#index'
  match 'signin', to: "customers#login", via: [:post]
  match "line_items/changequantity", to: "line_items#adjust_quantity", as: "changequantity", via: [:get]
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get]
  match "checkout/details", to: "orders#details", as: "checkout_details", via: [:get, :patch, :post]
  match "checkout/confirmationpage", to: "orders#confirmation_page", as: "confirmation_message", via: [:get, :patch, :post]
  match "/aboutus", to: "statics#about_us", as: "aboutus", via: [:get, :patch, :post]
  match "/contactus", to: "statics#contact_us", as: "contactus", via: [:get, :patch, :post]
  match "/careers", to: "statics#careers", as: "careers", via: [:get, :patch, :post]
  match "/policy", to: "statics#policy", as: "policy", via: [:get, :patch, :post]
  

end

app/models/store.rb
class Store < ActiveRecord::Base
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	def index
		@vendors = User.all
		if params[:city].present? or params[:location].present?

			address = "#{params[:city]}"+','+"#{params[:area]}"
			session[:address] = address
			#location = Geocoder.search(address)
			@vendors = @vendors.near(session[:address], 15, :units => :km)
		end
		if params[:free_delivery].present?
			@vendors = @vendors.where(:free_delivery => true)
  	end
  	respond_to do |format|
			format.js {}
			format.html
			format.json{}
		end
	end

	def show
	end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_categories_filter.html.erb
<ul class="list-unstyled">
  <li>
    <a href="#">
      fast food
    </a>
  </li>
  <li>
    <a href="#">
      Pizza
    </a>
  </li>
  <li>
    <a href="#">
      Pakistani
    </a>
  </li>
  <li>
    <a href="#">
      BBQ & Grills
    </a>
  </li>
  <li>
    <a href="#">
      Chinese
    </a>
  </li>
  <li>
    <a href="#">
      Dessert
    </a>
  </li>
  <li>
    <a href="#">
      Italian
    </a>
  </li>
  <li>
    <a href="#">
      Seafood
    </a>
  </li>
  <li>
    <a href="#">
      Beverages
    </a>
  </li>
  <li>
    <a href="#">
      Cake
    </a>
  </li>
  <li>
    <a href="#">
      Steaks
    </a>
  </li>
  <li>
    <a href="#">
      cafe
    </a>
  </li>
  <li>
    <a href="#">
      Fried chicken
    </a>
  </li>
  <li>
    <a href="#">
      Healthy fast food
    </a>
  </li>
  <li>
    <a href="#">
      Sandwiches
    </a>
  </li>
  <li>
    <a href="#">
      Afghan
    </a>
  </li>
  <li>
    <a href="#">
      Arabic
    </a>
  </li>
  <li>
    <a href="#">
      Bakery
    </a>
  </li>
  <li>
    <a href="#">
      Burgers
    </a>
  </li>
  <li>
    <a href="#">
      Flame grilled chicken experts
    </a>
  </li>
  <li>
    <a href="#">
      Icecream
    </a>
  </li>
  <li>
    <a href="#">
      Indian
    </a>
  </li>
  <li>
    <a href="#">
      Roll
    </a>
  </li>
  <li>
    <a href="#">
      Specialty paratha
    </a>
  </li>
  <li>
    <a href="#">
      Thai
    </a>
  </li>
</ul>

app/views/stores/_filter_headings.html.erb
<div class="filters">
  <div class="form-group">
    <i class="fa fa-sort-amount-desc"></i>
    <select class="form-control">
      <option value selected="selected">Sort By Relevance</option>
      <option value="default">Revelance</option>
      <option value="">Ratings</option>
      <option>Minimum Order Value</option>
      <option value="">Free Delivery</option>
      <option value="">Fastest Delivery</option>
    </select>
  </div>
</div>

app/views/stores/_nav_bar.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><a href="#">Stores</a></li>
    <li class="active"><%=params[:area]%>,<%=params[:city]%></li>
  </ol>
</div>

app/views/stores/_oldall_stores.html.erb
<% @vendors.each do |vendor|%>
  <div class="clickable" >
    <a href="/stores/<%=vendor.id%>">
      <div class="define-border">
        <div class="row">
          <div class="col-md-2">
            <a href="/stores/<%= vendor.id%>"><img src="<%= vendor.avatar.url %>" class="img-responsive center-block"></a> 
          </div>
          <div class="col-md-8">
            <h4><%= vendor.name%></h4>
            <div class="a-tag">
            <% if vendor.vendor_category_id %>
              <% id = vendor.vendor_category_id %>
              <a href="#"><%= Admin::VendorCategory.find_by_id(id).name%></a>
            <%end%>
    </div>

    <ul class="list-unstyled list-inline">
    <li><a href="#" style="">$$$</a></li>
    <li>
    <i class="fa fa-star fa-fw"></i> 
    <i class="fa fa-star fa-fw"></i> 
    <i class="fa fa-star-half-o fa-fw"></i>
    <i class="fa fa-star-o fa-fw"></i>
    </li>
    </ul>
    <div class="time">Delivers in <%= vendor.delivery_time rescue ''%></div>
    </div>
    <div class="vendor__promoted"><span>NEW</span></div>
    </div>
    </div>
    </a>
  </div>
<%end%>

app/views/stores/_pagination.html.erb
<nav class="text-right">
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
      <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

app/views/stores/_search_filter.html.erb
<div class="col-md-3">
 
  <div class="filters">
    <div class="form-group">
      <i class="fa fa-search"></i>
      <input type="text" name="" class="form-control" required="required" placeholder="Search">
    </div>
  </div>

  <div class="filters">
    <div class="form-group">
      <i class="fa fa-sort-amount-desc"></i>
      
      <select class="form-control">
        <option value selected="selected">Sort By Relevance</option>
        <option value="default">Revelance</option>
        <option value="">Ratings</option>
        <option>Minimum Order Value</option>
        <option value="">Free Delivery</option>
        <option value="">Fastest Delivery</option>
      </select>
    </div>  

  </div>
  
  <div class="characteristics filters-area">
    
    <div class="filters-title list-1-js">
      <i class="fa fa-sliders fa-rotate-270"></i> <span>Filters</span>
    </div>

    
    <ul class="list-unstyled">
      <li>
        <a href="#">
          free delivery
        </a>
      </li>
      <li>
        <a href="#">
          
          Deals
        </a>
      </li>
      <li>
        <a href="#">
          
          Open Restaurants
        </a>
      </li>
      <li>
        <a href="#">
          
          Online Payment avaliable
        </a>
      </li>
      <li>
        <a href="#">
          
          fast delivery
        </a>
      </li>
      <li>
        <a href="#">
          
          Resturants own delivery
        </a>
      </li>
    </ul>
    
  </div>
  
  <div class="characteristics stores-list">
    
    <div class="filters-title list-2-js">
      <i class="fa fa-map-marker"></i> <span>Top Stores</span>
    </div>
<%= render 'stores_list'%>
    
  </div>
</div>

app/views/stores/_side_filters.html.erb
<%=form_tag stores_path, method: 'get', id: "filters", :remote=>true do%>
<div class="characteristics">
  <div class="filters-title">
    <i class="fa fa-sliders fa-rotate-270"></i> <span>Restaurants</span>
  </div>
<%= render 'search_filter'%>
</div>
<div class="characteristics">
  <div class="filters-title">
    <i class="fa fa-cutlery"></i> <span>Categories</span>
  </div>
  <%= render 'categories_filter'%>
</div>
<button type="submit" id="filter_btn" class="hidden">Submit</button>
<%end%>

app/views/stores/_store_index_banner_text.html.erb
<div class="homepage-tagline">
  <div class="homepage-headline">
    <h1>93 restaurants</h1>
    <h2>delivering to your door</h2>
  </div>
</div>
<div class="location-header">
  <div class="container">
    <i class="fa fa-map-marker fa-fw"></i> 
    <span class="current-location">Johar Town, Block-E, Lahore</span>
    <a href="#" class="btn btn-primary btn-xs change-location">Change Location</a>
  </div>
</div>

app/views/stores/_stores_list.html.erb
    <ul class="list-unstyled">
      <li>
        <a href="#">
          fast food
        </a>
      </li>
      <li>
        <a href="#">
          
          Pizza
        </a>
      </li>
      <li>
        <a href="#">
          
          Pakistani
        </a>
      </li>
      <li>
        <a href="#">
          
          BBQ & Grills
        </a>
      </li>
      <li>
        <a href="#">
          
          Chinese
        </a>
      </li>
      <li>
        <a href="#">
          
          Dessert
        </a>
      </li>
      <li>
        <a href="#">
          
          Italian
        </a>
      </li>
      <li>
        <a href="#">
          
          Seafood
        </a>
      </li>
      <li>
        <a href="#">
          
          Beverages
        </a>
      </li>
      <li>
        <a href="#">
          
          Cake
        </a>
      </li>
      <li>
        <a href="#">
          
          Steaks
        </a>
      </li>
      <li>
        <a href="#">
          
          cafe
        </a>
      </li>
      <li>
        <a href="#">
          
          Fried chicken
        </a>
      </li>
      <li>
        <a href="#">
          
          Healthy fast food
        </a>
      </li>
      <li>
        <a href="#">
          
          Sandwiches
        </a>
      </li>
      <li>
        <a href="#">
          
          Afghan
        </a>
      </li>
      <li>
        <a href="#">
          
          Arabic
        </a>
      </li>
      <li>
        <a href="#">
          
          Bakery
        </a>
      </li>
      <li>
        <a href="#">
          
          Burgers
        </a>
      </li>
      <li>
        <a href="#">
          
          Flame grilled chicken experts
        </a>
      </li>
      <li>
        <a href="#">
          
          Icecream
        </a>
      </li>
      <li>
        <a href="#">
          
          Indian
        </a>
      </li>
      <li>
        <a href="#">
          
          Roll
        </a>
      </li>
      <li>
        <a href="#">
          
          Specialty paratha
        </a>
      </li>
      <li>
        <a href="#">
          
          Thai
        </a>
      </li>
    </ul>

app/views/stores/index.html.erb
<%= render 'detail_banner'%>
 <div class="container">
  <div class="row">
  	<div class="margin-top">
  		<%= render 'search_filter'%>
  		<%= render 'all_stores'%>
  	</div>
  </div>
 </div>

<%= render 'shared/location_popup'%>

app/views/stores/index.js.erb
$('#all_stores').html("<%= escape_javascript render(:partial => 'stores/all_stores') %>");

app/views/stores/oldindex.html.erb
<div class="home-header" style="background-image: url(/assets/frontend/1.jpg);">
    <div class="homepage-tagline">
      <div class="homepage-headline">
       <!--  <h1>It's Time to Eat</h1>
        <h2>Order food from 1500+ restaurants.</h2> -->
      </div>
        <div class="homepage-content">
        <div class="text-center">
          <div class="form-inline">
          <%= form_tag('/stores', method: :get,:id=>"search_form", :class=>"search-box") do %>
            <div class="form-group">
              <%= select_tag :city, grouped_options_for_select(User::LOCATION_OPTIONS, params[:city]), class: 'form-control', :placeholder=> "Enter a city" %>
            </div>
            <div class="form-group user-area">
              <i class="fa fa-map-marker fa-fw"></i>
              <%=text_field_tag 'area',params[:area],:class=> "form-control", :placeholder=> "Enter an area"%>
            </div>
            <button type="submit" class="btn btn-success">Show Stores</button>
          <%end%>
          </div>
        </div>
      </div>
      </div>
  <%#= render 'store_index_banner_text'%>  
</div>
<%= render 'nav_bar'%>
<div class="container">
  <div class="row">
    <div class="margin-top">
      <div class="col-md-3">
        <div class="filters">
          <div class="form-group">
            <i class="fa fa-search"></i>
            <input type="text" name="" class="form-control" required="required" placeholder="Search">
          </div>
        </div>
        
        <%= render 'filter_headings'%>
        
        <%= render 'side_filters'%>

      </div>
      <div class="col-md-9">
        <div id="all_stores">
          <%= render 'all_stores'%>
        </div>
        <div class="clear"></div>
        <%#= render 'pagination'%>  
        <div class="clear20"></div>
      </div>
    </div>
  </div>
</div>
<div class="clear20"></div>