config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :vendor_categories
  end
  devise_for :customers , :controllers => { :registrations => 'customers_registration' }
  resources :customers

  devise_for :vendor_admins
  namespace :admin do
    resources :users
    resources :products
    resources :colors
    resources :sizes
    resources :orders
    resources :store_settings
    resources :testimonials
    resources :categories
    resources :deal_of_days
    end
  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
   get 'logout' => 'devise/sessions#destroy'
  end

 resources :carts
 resources :orders 
 resources :vendors
 resources :products, only: [:show, :index]
 resources :stores, only: [:show, :index]

 resources :admin, only: [:index]
  match "home/set_session" ,to: "home#change_languages", as: "languagepath", via: [:get]
  match "/newsletter" ,to: "statics#news_subscriber", as: "newssubscriber", via: [:post]
  match "admin/get_color_and_size" ,to: "admin/products#get_size_and_color_of_product", as: "getsizecolor", via: [:get]
  root 'home#index'
  match 'signin', to: "customers#login", via: [:post]
  match "line_items/changequantity", to: "line_items#adjust_quantity", as: "changequantity", via: [:get]
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get]
  match "checkout/details", to: "orders#details", as: "checkout_details", via: [:get, :patch, :post]
  match "checkout/confirmationpage", to: "orders#confirmation_page", as: "confirmation_message", via: [:get, :patch, :post]
  match "/aboutus", to: "statics#about_us", as: "aboutus", via: [:get, :patch, :post]
  match "/contactus", to: "statics#contact_us", as: "contactus", via: [:get, :patch, :post]
  match "/careers", to: "statics#careers", as: "careers", via: [:get, :patch, :post]
  match "/policy", to: "statics#policy", as: "policy", via: [:get, :patch, :post]
  

end

app/models/order.rb
class Order < ActiveRecord::Base
    has_many :line_items
    belongs_to :customer
     accepts_nested_attributes_for :customer, reject_if: :all_blank, allow_destroy: true
    #accepts_nested_attributes_for :customer
    has_one :address
    accepts_nested_attributes_for :address
    ORDER_NUMBER_LENGTH  = 9
    ORDER_NUMBER_LETTERS = false
    ORDER_NUMBER_PREFIX  = 'R'
    PAYMENT_TYPES = ["Cash On Delivery"]

    before_validation :generate_order_number, on: :create

 def generate_order_number(options = {})
	  options[:length]  ||= ORDER_NUMBER_LENGTH
	  options[:letters] ||= ORDER_NUMBER_LETTERS
	  options[:prefix]  ||= ORDER_NUMBER_PREFIX

	  possible = (0..9).to_a
	  possible += ('A'..'Z').to_a if options[:letters]

	  self.number ||= loop do
	    # Make a random number.
	    random = "#{options[:prefix]}#{(0...options[:length]).map { possible.shuffle.first }.join}"
	    # Use the random  number if no other order exists with it.
	    if self.class.exists?(number: random)
	      # If over half of all possible options are taken add another digit.
	      options[:length] += 1 if self.class.count > (10 ** options[:length] / 2)
	    else
	      break random
	    end
	  end
	end



	def vendor_based_sum(user_id)
		total=0
		line_items = self.line_items.where(user_id: user_id)
		line_items.each do |item| 
			if item.product and item.product.discounted_price.present?
				total+= item.quantity*item.product.discounted_price rescue '0'
			else 
				total+= item.quantity*item.product.price rescue 0
			end
		end
		return total
	end
	def sub_total
		total=0
		self.line_items.each do |item| 
			if item.product and item.product.discounted_price.present?
				total+= item.quantity*item.product.discounted_price rescue '0'
			else 
				total+= item.quantity*item.product.price rescue 0
			end
		end
		return total
	end


	def full_address
		address = self.address
		if address.present?
			"#{address.address}, #{address.city}, #{address.country_state}, #{address.country}"
		else
		"No address found"
		end		
	end

	def permanent_address
		address = self.customer.addresses.first
		
		if address.present?
			"#{address.address}, #{address.city}, #{address.country_state}, #{address.country}"
		else
		"No address found"
		end	
	end

	
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController

	def index
		if current_user.superadmin?
			@orders = Order.where(state: 'complete').order(created_at: :desc)
		else
			line_items_ids = LineItem.where(user_id: current_user.id).collect(&:id)
			@orders = Order.where(state: 'complete').joins(:line_items).where("line_items.id IN (?)",line_items_ids).order(created_at: :desc)
			# byebug
			# @orders = Order.where(state: 'complete').order(created_at: :desc)

		end
		if request.xhr?
	      if params[:user_id].present?
	        line_items_ids = LineItem.where(user_id: params[:user_id]).collect(&:id)
			@orders = Order.where(state: 'complete').joins(:line_items).where("line_items.id IN (?)",line_items_ids).order(created_at: :desc)
			# byebug
	        
	      else
	        @orders = Order.where(state: 'complete').order(created_at: :desc)
	      end
	    end

		respond_to do |format|
	        format.js {}
	        format.html
	    end
	end

	def show
		@order_detail=Order.find(params[:id])
		if current_user.superadmin?

		@line_items = @order_detail.line_items
	else
		@line_items = @order_detail.line_items.where(:user_id => current_user.id)
		
	end
		# byebug
		
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_session_order
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  # def index
  #   @orders = Order.all
  # end


  def check_session_order
    if @current_order.blank?
      redirect_to '/'
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  # def show
  # end

  # # GET /orders/new
  # def new
  #   @order = Order.new
  # end

  def checkout
    
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def checkout
 
    if current_customer
      redirect_to checkout_details_path
    else
      @customer  = Customer.new
    end

  end

  def details
    # byebug
    if params[:user].present?
     login_user(params)
      
    else
      # byebug
      #if @current_order.addresses.blank?
        @current_order.build_address
      #end 
      if request.patch?
        
        if @current_order.update(order_params)
            render :template => 'orders/confirmation_page'
           
        end
      end
    end
  end
  def confirmation_page
     @current_order.state = 'complete'
     @current_order.guest_token = SecureRandom.base64(24)
     @current_order.customer=current_customer if current_customer
     @current_order.save

     users=User.with_role :superadmin
     users.each do |user|
        UserMailer.order_confirmation(@current_order, user.email).deliver rescue ''
     end
     @current_order.line_items.group_by(&:user_id).each do |user,lineitems|
      emailaddress=User.find(user).email
      UserMailer.order_confirmation_vendor(lineitems, emailaddress).deliver rescue''
     end



     session['order_number']=nil
     redirect_to '/'
  end


  def login_user(params)
  customer = Customer.find_by_email(params[:user][:email])
  if customer.present?
     if customer.valid_password?(params[:user][:password])
      sign_in(:customer, customer)
      redirect_to checkout_details_path, :notice => "Signed in successfully."
      return
     end
  end
    redirect_to checkout_path, :alert => "Email or Password is invalid."
end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    session['order_number']=nil
    session['line_items_count']=0
    # byebug
    if @current_order and @current_order.line_items.present?

      @current_order.destroy
    end
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      # byebug
      params.require(:order).permit(:email_address,:phone,:email,:country,:country_state,:city,:phone,:first_name,:order_notes,:last_name,:delivery_name, address_attributes: [:id,:address_type,:address,:country,:country_state,:city ,:mobile_number])
    end
end

app/views/admin/orders/_users_list_orders.html.erb
<div style="">
    <select  class="form-control select" style="width:40%" onchange="fetch_specfic_vendor_sizes('/admin/orders',this.value)">
        <option value="">All Vendors</option>
        <% @users.each do |user| %>
            <option value="<%=user.id%>"><%=user.name%></option>
        
        <%end%>
    </select>
</div>

app/views/admin/orders/_vendor_orders.html.erb
<div class="dataTable_wrapper">
    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
            <tr>
                <th style="display:none;"></th>
                <th><%= t 'admin.firstname' %></th>
                <th><%= t 'admin.date' %></th>
                <th><%= t 'admin.number' %></th>
                <th><%= t 'admin.state' %></th>
                <th><%= t 'admin.paymentstate' %></th>
                <th><%= t 'admin.shipmentstate' %></th>
                <th><%= t 'admin.customeremail' %></th>
                <th><%= t 'admin.total' %></th>
                <th><%= t 'admin.tool' %></th>
            </tr>
        </thead>
        <tbody>

        <% @orders.each do |order| %>
            
            <tr class="odd gradeX">
            <td style="display: none;"></td>
                <td><%= order.first_name%></td>
                <td><%= order.created_at %></td>
                <td>
                    <%= link_to order.number,  admin_order_path(order), class: ""%>

                </td>
                <td><%= order.state rescue '' %></td>
                <td><%= order.payment_state%></td>
                <td><%= order.shipment_state%></td>
                <td><%=order.customer.email rescue ''%></td>
                 <td><%=store_unit%>
                 <%if current_user.superadmin?%>
                 <%=order.sub_total %>
                 <%else%>
                 <%= order.vendor_based_sum(current_user) %>
                 <%end%>
                     
                 </td>
                <td class="center">
                    <span><%#= link_to '', edit_admin_order_path(order),class: "edit fa fa-edit icon_link with-tip no-text", title: "edit" %> </span>
                    <span>
                        <%#= link_to '',  admin_order_path(order),  method: :delete, data: { confirm: 'Are you sure?' } ,class: "fa fa-trash icon_link with-tip no-text"%>
                    </span>
                </td>
            </tr>

        <% end %>                                                                             
        </tbody>
    </table>
</div>
<!-- /.table-responsive -->
<script>
    $(document).ready(function() {
        $('#dataTables-vendors').DataTable({
                responsive: true
        });
    });
</script>

app/views/admin/orders/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= t 'admin.allorders' %></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div <%if current_user.superadmin? %>style="float:left;"<%end%> class="panel-heading"><%= t 'admin.allorders' %>  </div>
                <%if current_user.superadmin? %>
                    <%=render :partial => 'users_list_orders'%>
                <%end%>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div  id="vendor_orders">
                    <%=render :partial => 'vendor_orders'%>
                    <!-- /.table-responsive -->
                </div>
                
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

app/views/admin/orders/index.js.erb
 $("#vendor_orders").html('<%=  j render(:partial => 'vendor_orders', :object => @orders) %>');

app/views/admin/orders/show.html.erb
<div class="row">
  <div class="col-md-12" style="background-color: #eee; height: 120px; ">
    <h2 class="text-center"> order actions</h2>
  </div>

</div>
<div class="row">
  <div class="col-md-8">
    <br>
    <% if @order_detail and @order_detail.line_items.present? %>      
      <div class="">
        <div class="row">
          <div class="table-responsive forms">
            <table class="table table-hover">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Total</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                 <% @line_items.each do |item| %>
                   <tr>
                       <td class="col-sm-8 col-md-6">
                          <div class="media">
                              <a class="pull-left" href="<%=product_path(item.product.id) rescue ''%>"><img class="media-object" src="<%= item.get_image %>" style="max-width: 72px;" class="img-responsive center-block"></a>
                              <div class="media-body">
                                  <h4 class="media-heading"><a href="<%=product_path(item.product.slug) rescue ''%>"><%= item.get_name %></a></h4>
                                  <h5 class="media-heading"> by <a href="/products?vendor=<%= item.product.user.id  %>"><%=item.product.user.name%></a></h5>
                                  <span>Status: </span><span class="text-success"><strong>In Stock</strong></span>
                              </div>
                          </div>
                       </td>
                       <td class="col-sm-1 col-md-1 text-center">
                            <%= item.quantity %>
                       </td>
                       <td class="col-sm-1 col-md-1 text-center">
                       <strong>
                       <%if item.product.discounted_price.present?%>
                          <%= show_price(item.product.discounted_price) %>
                       <%else%>
                          <%= show_price(item.product.price) %>
                       <%end%>
                       </strong></td>
                       <td class="col-sm-1 col-md-1 text-center"><strong><%= show_price(item.total) %></strong></td>
                       <td class="col-sm-1 col-md-1 text-right">
                          
                              
                         
                       </td>
                   </tr>
                <%end%>
               
                
                <tr>
                    <td>   </td>
                    <td>   </td>
                    <td>   </td>
                    <td><h5>Subtotal</h5></td>
                    <td class="text-right"><h5>
                    <strong>
                       <%if current_user.superadmin?%>
                          <%= show_price(@order_detail.sub_total) rescue 0%>
                        <%else%>
                          <%= show_price(@order_detail.vendor_based_sum(current_user)) rescue 0 %>
                       <%end%>
                    </strong></h5></td>
                </tr>
                <tr>
                    <td>   </td>
                    <td>   </td>
                    <td>   </td>
                    <td><h5>Estimated shipping</h5></td>
                    <td class="text-right"><h5><strong><%= show_price(0)%></strong></h5></td>
                </tr>
                <tr>
                    <td>   </td>
                    <td>   </td>
                    <td>   </td>
                    <td><h3>Total</h3></td>
                    <td class="text-right"><h3>
                    <strong>
                       <%if current_user.superadmin?%>
                          <%= show_price(@order_detail.sub_total) rescue 0%>
                          <%else%>
                          <%= show_price(@order_detail.vendor_based_sum(current_user)) rescue 0 %>
                       <%end%>

                    </strong></h3></td>
                </tr>
                
            </tbody>
                </table>
              </div>
        </div>
      </div>      


    <%end%>
  </div>
  <div class="col-md-4">
      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-info">
            <div class="panel-heading">
                Billing Address
            </div>
            <div class="panel-body">
                <p>
                    <table>
                        <tr>
                            <td><b style="position:relative; bottom: 15px;">Billing Address:</b></td>
                            <td><p><%=@order_detail.full_address rescue ''%></p><hr></td>

                            
                        </tr>

                        <tr>
                            <td><b style="position:relative; bottom: 15px;">Permanent Address:</b></td>
                            <td><p><%=@order_detail.permanent_address rescue 'Not Present'%></p><hr></td>
                            
                        </tr>
                        <tr>
                            <td><b style="position:relative; bottom: 15px;">Contact Number:</b></td>
                           
                            <td><p><%=@order_detail.phone rescue'NILL'%></p><hr></td>
                            
                            
                        </tr>
                    </table>
                </p>
            </div>
            
        </div>
      </div>
    </div>
    <div class="row">
        <div class="col-md-12">
          <div class="panel panel-info">
            <div class="panel-heading">
                Contact Details
            </div>
            <div class="panel-body">
                <p>
                    <table>
                        <tr>
                            <td ><b>First Name:</b></td>
                            <td class="padding10"><%=@order_detail.customer.first_name rescue @order_detail.first_name rescue 'Nill'%></td>
                            
                        </tr>
                        <tr>
                            <td ><b>Last Name:</b></td>
                            <td class="padding10"><%=@order_detail.customer.last_name rescue @order_detail.last_name rescue 'Nill'%></td>
                            
                        </tr>
                        <tr>
                            <td ><b>Phone Number:</b></td>
                            <td class="padding10"><%=@order_detail.customer.phone_number rescue @order_detail.phone rescue 'Nill' %></td>
                            
                        </tr>
                        <tr>
                            <td ><b>Mobile Number:</b></td>
                            <td class="padding10"><%=@order_detail.customer.mobile_number rescue @order_detail.phone rescue 'Nill'%></td>
                            
                        </tr>
                    </table>
                </p>
            </div>
            
        </div>
      </div>
    </div>
    <div class="row">
        <div class="col-md-12">
          <div class="panel panel-info">
            <div class="panel-heading">
                Order Notes
            </div>
            <div class="panel-body">
                <p>
                    <table>
                        <tr>
                          
                            <td class="padding10"><%=@order_detail.order_notes rescue''%></td>
                            
                        </tr>
                        
                    </table>
                </p>
            </div>
            
        </div>
      </div>
    </div>
      
  </div>
</div>

<style>
  .padding10{
    padding-left: 20px;
  }
</style>