config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :vendor_categories
  end
  devise_for :customers , :controllers => { :registrations => 'customers_registration' }
  resources :customers

  devise_for :vendor_admins
  namespace :admin do
    resources :users
    resources :products
    resources :colors
    resources :sizes
    resources :orders
    resources :store_settings
    resources :testimonials
    resources :categories
    resources :deal_of_days
    end
  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
   get 'logout' => 'devise/sessions#destroy'
  end

 resources :carts
 resources :orders 
 resources :vendors
 resources :products, only: [:show, :index]
 resources :stores, only: [:show, :index]

 resources :admin, only: [:index]
  match "home/set_session" ,to: "home#change_languages", as: "languagepath", via: [:get]
  match "/newsletter" ,to: "statics#news_subscriber", as: "newssubscriber", via: [:post]
  match "admin/get_color_and_size" ,to: "admin/products#get_size_and_color_of_product", as: "getsizecolor", via: [:get]
  root 'home#index'
  match 'signin', to: "customers#login", via: [:post]
  match "line_items/changequantity", to: "line_items#adjust_quantity", as: "changequantity", via: [:get]
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get]
  match "checkout/details", to: "orders#details", as: "checkout_details", via: [:get, :patch, :post]
  match "checkout/confirmationpage", to: "orders#confirmation_page", as: "confirmation_message", via: [:get, :patch, :post]
  match "/aboutus", to: "statics#about_us", as: "aboutus", via: [:get, :patch, :post]
  match "/contactus", to: "statics#contact_us", as: "contactus", via: [:get, :patch, :post]
  match "/careers", to: "statics#careers", as: "careers", via: [:get, :patch, :post]
  match "/policy", to: "statics#policy", as: "policy", via: [:get, :patch, :post]
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		# @admin_products = Admin::Product.all
		
		
		@featured_products=Admin::Product.where(:featured => "true").order(created_at: :desc)
		@best_selling=Admin::Product.where(:homepage => "true").order(created_at: :desc)
		@vendors = User.all
		if @vendors.present?
		  # Vendors within 10 Km
		  @vendors = @vendors.where(:popular => true)
		  if params[:latitude].present? and params[:longitude].present?
		  	if params[:latitude].first(6) != session[:latitude].first(6) and  params[:longitude].first(6) != session[:longitude].first(6)
		  		address = User.set_location(params[:latitude],params[:longitude])
		  	end
					# query.address
				session[:address] = address
		    session[:latitude] = params[:latitude]
		    session[:longitude] = session[:longitude]
		    @vendors = @vendors.near([params[:latitude], params[:longitude]], 15, :units => :km)
		    
		    	respond_to do |format|
		          format.js {}
		          format.html
		          format.json{}
		        end

		  end
		end

		



		# @featured_products=Admin::Product.where(:featured => "true").order(created_at: :desc)
		# @unfeatured_products=Admin::Product.where(:homepage => "true").order(created_at: :desc)
		# @admin_deal_of_days = Admin::DealOfDay.where('expiry_time >= ?', DateTime.now).order('expiry_time')

		# @testimonials = Admin::Testimonial.all
		# @categories_all=Admin::Category.all
		# # for brands
		# user_ids = Admin::Product.where.not(user_id: nil).collect(&:user_id).uniq
		# @brands=User.where(id: user_ids)
		# # brands end


		# if Admin::Category.second and Admin::Category.second.products.present? 
		# 	@category_two= Admin::Category.second.products.order("RANDOM()") 
		# 	@category_two_name=Admin::Category.second.name
		# else
		# 	@category_two= Admin::Category.fourth.products.order("RANDOM()")  rescue '' 
		# 	@category_two_name=Admin::Category.fourth.name  rescue ''

		# end


		# if Admin::Category.third and Admin::Category.third.products.present? 
		# 	@category_three= Admin::Category.third.products.order("RANDOM()")
		# 	@category_three_name=Admin::Category.third.name
		# else
		# 	@category_three= Admin::Category.fifth.products.order("RANDOM()") rescue ''
		# 	@category_three_name=Admin::Category.fifth.name rescue ''

		# end

		# if Admin::Category.first and Admin::Category.first.products.present? 
		# 	@category_one= Admin::Category.first.products.order("RANDOM()")
		# 	@category_one_name=Admin::Category.first.name
		# else
		# 	@category_one= Admin::Category.sixth.products.order("RANDOM()") rescue ''
		# 	@category_one_name=Admin::Category.sixth.name rescue ''

		# end
		
		
		
		

	end
	def change_languages
		session['language']= params[:lang]
		render :nothing => true
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_banner.html.erb
<div class="banner-area section-padding2">
	<div class="container">
		<div class="row">
			<div id="banner-slider">
				<%@categories_all.each do |cat|%>
					<div class="single-product banners">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 all_products_fix_images_small">
							<div class="banner-image product-img_small">
								<a href="/products?category=<%=cat.slug%>">
									<img src="<%=cat.image.avatar.url(:original) rescue ''%>" alt="">
								</a>
							</div>
						</div>	
					</div>
				<%end%>
			</div>
		</div>
	</div>
</div>















<!-- 
<div class=" col-lg-4 col-md-4 col-sm-4 col-xs-12">
	<div class="banner-image indicator-banner">
		<a href="#">
			<img src="/assets/banner/1.jpg" alt="">
		</a>
	</div>
	<div class="banner-image">
		<a href="#">
			<img src="/assets/banner/2.jpg" alt="">
		</a>
	</div>
</div>
<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
	<div class="banner-image">
		<a href="#">
			<img src="/assets/banner/3.jpg" alt="">
		</a>
	</div>
</div>
<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
	<div class="banner-image">
		<a href="#">
			<img src="/assets/banner/4.jpg" alt="">
		</a>
	</div>
</div>	 -->

app/views/home/_banner_with_detail.html.erb
<!--////////////////////////////////////////////////////////////////////////-->
<div class="home-header" style="background-image: url(/assets/commerce/header-img-5.jpg);">
  <div class="backdrop"></div>
  <div class="container backdrop-top">
    <div class="homepage-tagline">
      <div class="homepage-headline">
        <h1>SHOP With Confidence</h1>
        <h2>Order products from 1500+ stores</h2>
      </div>
      <div class="homepage-content">
        <div class="text-center">
          <div class="form-inline">
           <%= form_tag('/stores', method: :get,:id=>"search_form", :class=>"search-box") do %>
              <div class="form-group">
                <%= select_tag :city, grouped_options_for_select(User::LOCATION_OPTIONS,'Lahore'), class: 'form-control', :placeholder=> "Enter a city" %>
              </div>
              <div class="form-group user-area">
                <i class="fa fa-map-marker fa-fw"></i>
                <%=text_field_tag 'area','',:class=> "form-control", :placeholder=> "Enter an area"%>
              </div>
              <button type="submit" class="btn btn-success">Show Stores</button>
            <%end%>
          </div>
        </div>
      </div>  
    </div>
  </div>
</div>
<!--////////////////////////////////////////////////////////////////////////-->

app/views/home/_best_seller.html.erb
    <div class="section-title">
    	<h2>Our Bestsellers</h2>
    </div>

    <div id="owl-demo" class="owl-carousel owl-theme">
    	<%@featured_products.each do |product|%>
      <div class="item">
        <!--////////////////////////////////////////////////////////////////////////-->   
        <div class="product-wrapper">
         <div class="product-box">
          <%=link_to(image_tag('/assets/commerce/product-1.jpg'),product_path(product), :class=>"img-responsive center-block") %>
       </div>
       <div class="details">
        <div class="name"><%=product.name%></div>
        <div class="price"><%=show_price(product.discounted_price)%><span class="price-original"><%=show_price(product.price)%></span></div>
        <div class="clear10"></div>
        <div class="store-name">
          <%=link_to "Store: "+"#{product.user.name}",  vendor_path(product.user)%>
        </div>
        <div class="clear10"></div>
        <div class="text-center">
         <div class="btn-group" role="group" aria-label="...">
           <%=link_to "View Product",  product_path(product), class: 'btn btn-default btn-sm'%>
           <%=link_to "View Store",  vendor_path(product.user), class: 'btn btn-default btn-sm'%>
          
        </div>
      </div>
    </div>
  </div>
  <!--////////////////////////////////////////////////////////////////////////-->  

</div>
<%end%>
<div class="item">
  <!--////////////////////////////////////////////////////////////////////////-->   
  <div class="product-wrapper">
   <div class="product-box">
    <a href="#">
     <img src="/assets/commerce/product-2.png" class="img-responsive center-block">
   </a>
 </div>
 <div class="details">
  <div class="name">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, pariatur?</div>
  <div class="price">500 PKR <span class="price-original">800 PKR</span></div>
  <div class="clear10"></div>
  <div class="store-name"><a href="#">Store: Chen One</a></div>
  <div class="clear10"></div>
  <div class="text-center">
   <div class="btn-group" role="group" aria-label="...">
    <a  href="#" class="btn btn-default btn-sm">View Product</a>
    <a  href="#" class="btn btn-default btn-sm">View Store</a>
  </div>
</div>
</div>
</div>
<!--////////////////////////////////////////////////////////////////////////--> 
</div>
<div class="item">
  <!--////////////////////////////////////////////////////////////////////////-->   
  <div class="product-wrapper">
   <div class="product-box">
    <a href="#">
     <img src="/assets/commerce/product-3.png" class="img-responsive center-block">
   </a>
 </div>
 <div class="details">
  <div class="name">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, pariatur?</div>
  <div class="price">500 PKR <span class="price-original">800 PKR</span></div>
  <div class="clear10"></div>
  <div class="store-name"><a href="#">Store: Chen One</a></div>
  <div class="clear10"></div>
  <div class="text-center">
   <div class="btn-group" role="group" aria-label="...">
    <a  href="#" class="btn btn-default btn-sm">View Product</a>
    <a  href="#" class="btn btn-default btn-sm">View Store</a>
  </div>

</div>
</div>
</div>
<!--////////////////////////////////////////////////////////////////////////--> 
</div>
<div class="item">
  <!--////////////////////////////////////////////////////////////////////////-->   
  <div class="product-wrapper">
   <div class="product-box">
    <a href="#">
     <img src="/assets/commerce/product-4.png" class="img-responsive center-block">
   </a>
 </div>
 <div class="details">
  <div class="name">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, pariatur?</div>
  <div class="price">500 PKR <span class="price-original">800 PKR</span></div>
  <div class="clear10"></div>
  <div class="store-name"><a href="#">Store: Chen One</a></div>
  <div class="clear10"></div>
  <div class="text-center">
   <div class="btn-group" role="group" aria-label="...">
    <a  href="#" class="btn btn-default btn-sm">View Product</a>
    <a  href="#" class="btn btn-default btn-sm">View Store</a>
  </div>


</div>
</div>
</div>
<!--////////////////////////////////////////////////////////////////////////--> 
</div>

<div class="item">
  <!--////////////////////////////////////////////////////////////////////////-->   
  <div class="product-wrapper">
   <div class="product-box">
    <a href="#">
     <img src="/assets/commerce/product-5.png" class="img-responsive center-block">
   </a>
 </div>
 <div class="details">
  <div class="name">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, pariatur?</div>
  <div class="price">500 PKR <span class="price-original">800 PKR</span></div>
  <div class="clear10"></div>
  <div class="store-name"><a href="#">Store: Chen One</a></div>
  <div class="clear10"></div>
  <div class="text-center">
   <div class="btn-group" role="group" aria-label="...">
    <a  href="#" class="btn btn-default btn-sm">View Product</a>
    <a  href="#" class="btn btn-default btn-sm">View Store</a>
  </div>


</div>
</div>
</div>
<!--////////////////////////////////////////////////////////////////////////--> 
</div>
<div class="item">
  <!--////////////////////////////////////////////////////////////////////////-->   
  <div class="product-wrapper">
   <div class="product-box">
    <a href="#">
     <img src="/assets/commerce/product-1.jpg" class="img-responsive center-block">
   </a>
 </div>
 <div class="details">
  <div class="name">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, pariatur?</div>
  <div class="price">500 PKR <span class="price-original">800 PKR</span></div>
  <div class="clear10"></div>
  <div class="store-name"><a href="#">Store: Chen One</a></div>
  <div class="clear10"></div>
  <div class="text-center">
   <div class="btn-group" role="group" aria-label="...">
    <a  href="#" class="btn btn-default btn-sm">View Product</a>
    <a  href="#" class="btn btn-default btn-sm">View Store</a>
  </div>
</div>
</div>
</div>
<!--////////////////////////////////////////////////////////////////////////-->  

</div>
<div class="item">
  <!--////////////////////////////////////////////////////////////////////////-->   
  <div class="product-wrapper">
   <div class="product-box">
    <a href="#">
     <img src="/assets/commerce/product-2.png" class="img-responsive center-block">
   </a>
 </div>
 <div class="details">
  <div class="name">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, pariatur?</div>
  <div class="price">500 PKR <span class="price-original">800 PKR</span></div>
  <div class="clear10"></div>
  <div class="store-name"><a href="#">Store: Chen One</a></div>
  <div class="clear10"></div>
  <div class="text-center">
   <div class="btn-group" role="group" aria-label="...">
    <a  href="#" class="btn btn-default btn-sm">View Product</a>
    <a  href="#" class="btn btn-default btn-sm">View Store</a>
  </div>


</div>
</div>
</div>
<!--////////////////////////////////////////////////////////////////////////--> 
</div>
</div> <!--////////////////////////////owl carousel ends///////////////////////////////////--> 

app/views/home/_blog.html.erb
<div class="blog-area section-padding">
    <div class="container">
		<div class="section-title">
			<h4><%= t 'welcome.fromtheblog' %></h4>
		</div>
        <div class="row">
            <div class="blog-list indicator-style">
                <div class="col-md-4">
                    <div class="single-blog">
                        <div class="blog-image">
                            <a href="blog-details.html">
                                <img src="/assets/blog/1.jpg" alt="">
                            </a>
                        </div>
                        <div class="blog-content">
                            <h5><a href="blog-details.html">Share the Love for PrestaShop 1.6</a></h5>
                            <div class="date-added">2015-12-28 04:28:04</div>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="single-blog">
                        <div class="blog-image">
                            <a href="blog-details.html">
                                <img src="/assets/blog/2.jpg" alt="">
                            </a>
                        </div>
                        <div class="blog-content">
                            <h5><a href="blog-details.html">Answers to your Questions about...</a></h5>
                            <div class="date-added">2015-12-28 04:28:04</div>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...</p>
                        </div>
                    </div>                   
                </div>
                <div class="col-md-4">
                    <div class="single-blog">
                        <div class="blog-image">
                            <a href="blog-details.html">
                                <img src="/assets/blog/3.jpg" alt="">
                            </a>
                        </div>
                        <div class="blog-content">
                            <h5><a href="blog-details.html">What is Bootstrap? – The History...</a></h5>
                            <div class="date-added">2015-12-28 04:28:04</div>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="single-blog">
                        <div class="blog-image">
                            <a href="blog-details.html">
                                <img src="/assets/blog/4.jpg" alt="">
                            </a>
                        </div>
                        <div class="blog-content">
                            <h5><a href="blog-details.html">From Now we are certified web...</a></h5>
                            <div class="date-added">2015-12-28 04:28:04</div>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>	        
    </div>
</div>

app/views/home/_brand.html.erb
<div class="brand-area section-padding2">
    <div class="container">
        <div class="row">		            
            <div class="brand-list">

                <% @brands.each do |brand|%>
                <div class="col-md-12">
                    <div class="single-brand">
                        <a href="/products?vendor=<%= brand.id %>"><img style="border-radius:100%" src="<%=brand.avatar.url(:thumbnail) rescue ''%>" alt=""></a>
                    </div>
                </div>
                <%end%>
            </div>
        </div>
    </div>
</div>

app/views/home/_featured.html.erb
<div class="featured-area section-padding">
    <div class="container">
		<div class="section-title">
			<h4><%= t 'welcome.featured' %></h4>
		</div>
        <div class="row">
			<!--Product List Start-->
			<div class="featured-product-list indicator-style all_products_fix_images">
				<% @featured_products.each do |product| %>
					<!--Single Product -->
					<div class="col-md-3 col-sm-6">
						<div class="single-product">
							<!--product Content-->
							<div class="product-img-content">
								<!--Product Image-->
								<div class="product-img">
									<a href="<%=product_path(product.slug)%>" title="<%= product.name %>">
										<%if product.images.present? %>
											<%=image_tag product.images.first.avatar.url(:large)%>
                                        <%else%>
                                            <img src="http://s3.amazonaws.com/commerceassets/admin/images/avatars/000/000/089/large/data?1473265319"/>
										<%end%> 

									</a>		                                    
								</div>
								<span class="new-label"><%= t 'welcome.new' %></span>
								<%if product.discounted_price?%>
									<span class="sale-label">!<%= t 'welcome.sale' %></span>
								<%end%>
								

								<!--Product Action-->
								<div class="product-action"> 
									<a  title="<%= t 'welcome.addtocart' %>" onclick="getProductDetail(this)"><i class="fa fa-shopping-cart"><%= hidden_field_tag :product_id,{}, :value=>"#{product.slug}"  %></i></a>
									<a  title="<%= t 'welcome.quickview' %>"  onclick="getProductDetail(this)" >
									<i class="fa fa-expand">
									<%= hidden_field_tag :product_id,{}, :value=>"#{product.slug}"  %></i>
									</a>
								</div>
							</div>
							<div class="product-content">
								<h5 class="clearfix">
									<div class="pull-left"><a href="<%=product_path(product.slug)%>" title="<%= product.name %>"><%= product.name %></a></div>
									<div class="pull-right"><a href="/products?vendor=<%= product.user.id %>" title="<%= product.user.name %>"><%= product.user.name%></a></div>
								</h5>
								<!--Product Rating-->
								<div class="rating-icon">
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
								</div>
								<!--Product Price-->
								<div class="product-price">
									<%if product.discounted_price?%>
									<span class="new-price"> <%= show_price(product.discounted_price) %> </span>
									<span class="old-price"><%=show_price(product.price ) %></span>
									<%else%>
									<span class="new-price"><%=show_price(product.price)  %></span>
									<%end%>
									
								</div>
							</div>
						</div>
					</div>
					<!--Single Product -->
				<% end %> 
			</div>
			<!--Product List Start-->
        </div>
    </div>
</div>

app/views/home/_new_products.html.erb
<div class="featured-area section-padding">
    <div class="container">
		<div class="section-title">
			<h4><%= t 'welcome.newproducts' %></h4>
		</div>
        <div class="row">
			<!--Product List Start-->
			<div class="featured-product-list indicator-style all_products_fix_images">
				


				<% @unfeatured_products.each do |product| %>

					<!--Single Product -->
					<div class="col-md-3 col-sm-6">
						<div class="single-product">
							<!--product Content-->
							<div class="product-img-content">
								<!--Product Image-->
								<div class="product-img">
									<a href="<%=product_path(product.slug)%>" title="<%= product.name %>">
										<%if product.images.present? %>
											<%=image_tag product.images.first.avatar.url(:large)%>
                                        <%else%>
                                            <img src="http://s3.amazonaws.com/commerceassets/admin/images/avatars/000/000/089/large/data?1473265319"/>
										<%end%> 

									</a>		                                    
								</div>
								<span class="new-label"><%= t 'welcome.new' %></span>
								<%if product.discounted_price?%>
									<span class="sale-label">!<%= t 'welcome.sale' %></span>
								<%end%>
								

								<!--Product Action-->
								<div class="product-action"> 
									<a  title="<%= t 'welcome.addtocart' %>" onclick="getProductDetail(this)"><i class="fa fa-shopping-cart"><%= hidden_field_tag :product_id,{}, :value=>"#{product.slug}"  %></i></a>
									<a  title="<%= t 'welcome.quickview' %>"  onclick="getProductDetail(this)" >
									<i class="fa fa-expand">
									<%= hidden_field_tag :product_id,{}, :value=>"#{product.slug}"  %></i>
									</a>
								</div>
							</div>
							<div class="product-content">
								<h5 class="clearfix">
									<div class="pull-left"><a href="<%=product_path(product.slug)%>" title="<%= product.name %>"><%= product.name %></a></div>
									<div class="pull-right"><a href="/products?vendor=<%= product.user.id rescue''%>" title="<%= product.user.name rescue'' %>"><%= product.user.name rescue''%></a></div>
								</h5>
								<!--Product Rating-->
								<div class="rating-icon">
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
								</div>
								<!--Product Price-->
								<div class="product-price">
									<div class="product-price">
									<%if product.discounted_price?%>
									<span class="new-price"> <%= show_price(product.discounted_price) %> </span>
									<span class="old-price"><%=show_price(product.price ) %></span>
									<%else%>
									<span class="new-price"><%=show_price(product.price)  %></span>
									<%end%>
								</div>
									
								</div>
							</div>
						</div>
					</div>
					<!--Single Product -->
				

				<% end %> 







			</div>
			<!--Product List Start-->
        </div>	
    </div>
</div>

app/views/home/_newsletter.html.erb
<div class="news-letter-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-7  col-sm-7 col-xs-12">
				<div class="banner-image">
					<a href="#">
						<img src="/assets/news-letter.jpg" alt="">
					</a>
				</div>		                
            </div>
            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                <div class="letter-box">
                    <div class="letter-title">
                        <h4><%= t 'welcome.newsletter' %></h4>
                        <i class="fa fa-envelope-o"></i>
                    </div>
                    <p>Subscribe to our email newsletter & receive updates right in your inbox.</p>
                    <div class=" message">
                        	
                        </div>
                    <%= form_tag("/home/newsletter", method: "post" ,:remote => true,:class => 'search-box')  do %>
                        <div>
							<input type="email" name="email_user" id="search-letter" placeholder ="<%= t 'welcome.enteryouremail' %>">
                            <button type="submit" id="search-letter-btn" class="btn btn-search">
                                <i class="fa fa-paper-plane-o"></i>
                            </button>
                        </div>
                    <%end%>
                    
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/_popular_vendors.html.erb
<div class="container"> 

	<div class="section-title">
		<h2>
			Popular Brands
		</h2>
	</div>

	<div class="owl-wrapper-custom">
		<div class="owl-carousel owl-theme">
			<div class="item"><img src="/assets/commerce/brand-1.jpg" class="img-responsive center-block"></div>
			<div class="item"><img src="/assets/commerce/brand-2.jpg" class="img-responsive center-block"></div>
			<div class="item"><img src="/assets/commerce/brand-3.jpg" class="img-responsive center-block"></div>
			<div class="item"><img src="/assets/commerce/brand-4.jpg" class="img-responsive center-block"></div>
			<div class="item"><img src="/assets/commerce/brand-5.jpg" class="img-responsive center-block"></div>
			<div class="item"><img src="/assets/commerce/brand-1.jpg" class="img-responsive center-block"></div>
			<div class="item"><img src="/assets/commerce/brand-2.jpg" class="img-responsive center-block"></div>
			<div class="item"><img src="/assets/commerce/brand-3.jpg" class="img-responsive center-block"></div>
			<div class="item"><img src="/assets/commerce/brand-4.jpg" class="img-responsive center-block"></div>
			<div class="item"><img src="/assets/commerce/brand-5.jpg" class="img-responsive center-block"></div>
		</div>
		
	</div>
</div> 

app/views/home/_slider.html.erb
<div class="slider-area">
        <div class="slider-area">
            <div class="bend niceties preview-1">
				<div id="ensign-nivoslider-3" class="slides">   
				   <a href="#"><img src="/assets/slider/1.jpg" alt=""/></a>
				   <a href="#"> <img src="/assets/slider/2.jpg" alt=""/></a>
				</div>
            </div>
        </div>
</div>

app/views/home/_slider_single_product.html.erb
<%a=2%>
<% items.each_with_index do |product, index|%>
	<%if index%3 == 0 %>
		<div class="single-p-item">
	<%end%>


		<div class="single-product">
			<div class="col-lg-6 col-md-6 col-sm-12 col-xs-6 ">

				<div class="all_products_fix_images_small">
					<a href="<%=product_path(product.slug)%>" title="<%= product.name %>">
						<div class="product-img_small">
						<%if product.images.present? %>
							<%=image_tag product.images.first.avatar.url(:large), :class => "img-responsive	 center-block"%>
						<%else%>
                            <img src="http://s3.amazonaws.com/commerceassets/admin/images/avatars/000/000/089/large/data?1473265319"/>
						<%end%>
						</div>
					</a>
						                                    
				</div>                                        
			</div>
			<div class="col-lg-6 col-md-6 col-sm-12 col-xs-6">
				<div class="product-content">
					<h5><a href="<%=product_path(product.slug)%>" title="<%= product.name %>"><%= product.name %></a></h5>
					<!--Product Rating-->
					<div class="rating-icon">
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
					</div>
					<!--Product Price-->
					<div class="product-price">
						<%if product.discounted_price?%>
						<span class="new-price"> <%= show_price(product.discounted_price) %> </span>
						<span class="old-price"><%=show_price(product.price ) %></span>
						<%else%>
						<span class="new-price"><%=show_price(product.price)  %></span>
						<%end%>
					</div>	
				</div>
			</div>
		</div> 
	<%if index == (items.length-1) or index==2 %>

		</div>
	<%end%>
	<%if  index-a == 3 and (index != (items.length-1))%>
		</div>
		<%a=index%>
	<%end%>

<%end%>

app/views/home/index.html.erb
<%= render 'banner_with_detail' %>
<%#= render 'store_description' %>
<div class="container">
<%= render 'best_seller' %>
</div>
<div class="container">
<%= render 'featured_product' %>
</div>
<%= render 'store_description' %>
<%= render 'popular_vendors' %>
<div class="clear40"></div>
<div class="clear40"></div>