config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :vendor_categories
  end
  devise_for :customers , :controllers => { :registrations => 'customers_registration' }
  resources :customers

  devise_for :vendor_admins
  namespace :admin do
    resources :users
    resources :products
    resources :colors
    resources :sizes
    resources :orders
    resources :store_settings
    resources :testimonials
    resources :categories
    resources :deal_of_days
    end
  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
   get 'logout' => 'devise/sessions#destroy'
  end

 resources :carts
 resources :orders 
 resources :vendors
 resources :products, only: [:show, :index]
 resources :stores, only: [:show, :index]

 resources :admin, only: [:index]
  match "home/set_session" ,to: "home#change_languages", as: "languagepath", via: [:get]
  match "/newsletter" ,to: "statics#news_subscriber", as: "newssubscriber", via: [:post]
  match "admin/get_color_and_size" ,to: "admin/products#get_size_and_color_of_product", as: "getsizecolor", via: [:get]
  root 'home#index'
  match 'signin', to: "customers#login", via: [:post]
  match "line_items/changequantity", to: "line_items#adjust_quantity", as: "changequantity", via: [:get]
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get]
  match "checkout/details", to: "orders#details", as: "checkout_details", via: [:get, :patch, :post]
  match "checkout/confirmationpage", to: "orders#confirmation_page", as: "confirmation_message", via: [:get, :patch, :post]
  match "/aboutus", to: "statics#about_us", as: "aboutus", via: [:get, :patch, :post]
  match "/contactus", to: "statics#contact_us", as: "contactus", via: [:get, :patch, :post]
  match "/careers", to: "statics#careers", as: "careers", via: [:get, :patch, :post]
  match "/policy", to: "statics#policy", as: "policy", via: [:get, :patch, :post]
  

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	

	def index
		
	end
	def create
		product = Admin::Product.find_by_id(params[:product_id])
		unless @current_order
			@current_order = Order.create(:state => :cart)
			# byebug
			session['order_number'] = @current_order.number
		end
		# if @current_order.line_items.present? and  @current_order.line_items.collect(&:product_id).include? params[:product_id].to_i and @current_order.line_items.collect(&:size_id).include? params[:size_id].to_i and @current_order.line_items.collect(&:color_id).include? params[:color_id].to_i
			line_item = @current_order.line_items.where(:product_id=> params[:product_id],:size_id => params[:size_id],:color_id=> params[:color_id]).first
			if line_item.present?
				line_item.quantity += params[:quantity].to_i
				line_item.save 
			# end
		else


			line_itm = LineItem.create(:user_id=>product.user.id , :quantity => params[:quantity],:product_id => product.id ,:order_id => @current_order.id,:size_id => params[:size_id] ,:color_id => params[:color_id])
		end

		
		@current_order = Order.find_by_number(session['order_number'])
		# if request.xhr?
		# 	# byebug
		# 	session['line_items_count'] = @current_order.line_items.count rescue '0'
		# 	render :partial => "subcart"
		# else
		# 	render :nothing => true
		# end
		
		respond_to do |format|
	        format.js {render "create", :locals => {:count => @current_order}}
	        format.html
      	end
	end

	def destroy

		LineItem.destroy(params[:id])
		respond_to do |format|
	        format.js {}
	        format.html
      	end
		
	end
	
end

app/views/carts/_cart_table.html.erb
<% if @current_order and @current_order.line_items.present? %>      
  <div class="container">
    <div class="row">
      <div class="table-responsive forms">
        <table class="table table-hover">
    <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th class="text-center">Price</th>
            <th class="text-center">Total</th>
            <th> </th>
        </tr>
    </thead>
    <tbody>
         <% @current_order.line_items.each do |item| %>
           <tr>
               <td class="col-sm-8 col-md-6">
                  <div class="media">
                      <a class="pull-left" href="<%=product_path(item.product.id)%>"><img class="media-object" src="<%= item.get_image %>" style="max-width: 72px; max-height: 72px;" class="img-responsive"></a>
                      <div class="media-body">
                          <h4 class="media-heading"><a href="<%=product_path(item.product.id)%>"><%= item.get_name %></a></h4>
                          <h5 class="media-heading"> by <a href="/products?vendor=<%= item.product.user.id %>"><%=item.product.user.name%></a></h5>
                          <span>Status: </span><span class="text-success"><strong>In Stock</strong></span>
                      </div>
                  </div>
               </td>
               <td class="col-sm-1 col-md-1 text-center">
               <input type="number" min="1" max="2147483646" class="form-control" onchange="quantitychange(this.value,<%= item.id%>)" value="<%= item.quantity %>">
               </td>
               <td class="col-sm-1 col-md-1 text-center">
               <strong>
               <%if item.product.discounted_price.present?%>
                  <%= show_price(item.product.discounted_price) %>
               <%else%>
                  <%= show_price(item.product.price) %>
               <%end%>
               </strong></td>
               <td class="col-sm-1 col-md-1 text-center"><strong><%= show_price(item.total) %></strong></td>
               <td class="col-sm-1 col-md-1 text-right">
                  
                      <%= link_to cart_path(item), method: :delete, confirm: 'Delete?', class: 'btn btn-danger remove-item', 'data-message' => 'Are you sure?', 'data-severity' => 'danger', :remote => true do %>
                        <span class="glyphicon glyphicon-remove"></span>
                        <%end%>
                 
               </td>
           </tr>
        <%end%>
       
        </tr> 
        <tr>
            <td>   </td>
            <td>   </td>
            <td>   </td>
            <td><h5>Subtotal</h5></td>
            <td class="text-right"><h5>
            <strong>
               <%if @current_order.present?%>
                  <%= show_price(@current_order.sub_total) %>
               <%end%>
            </strong></h5></td>
        </tr>
        <tr>
            <td>   </td>
            <td>   </td>
            <td>   </td>
            <td><h5>Estimated shipping</h5></td>
            <td class="text-right"><h5><strong><%= show_price(0)%></strong></h5></td>
        </tr>
        <tr>
            <td>   </td>
            <td>   </td>
            <td>   </td>
            <td><h3>Total</h3></td>
            <td class="text-right"><h3>
            <strong>
               <%if @current_order.present?%>
                  <%= show_price(@current_order.sub_total) %>
               <%end%>

            </strong></h3></td>
        </tr>
        <tr>
            <td colspan="5" class="text-right">
               <a type="button" class="btn btn-default" href="/">
                   <span class="glyphicon glyphicon-shopping-cart"></span> Continue Shopping
               </a>
               
                <%= link_to 'Empty Cart', order_path(@current_order),
            method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn btn-warning'%>

                <a type="button" href="<%= checkout_path %>" class="btn btn-success">
                   Checkout
               </a>
            </td>

        </tr>
    </tbody>
        </table>
      </div>
    </div>
  </div>      
<%else%>
 <center>
    <br>
    <h1>CART EMPTY</h1>
    <a type="button" class="btn btn-default" href="/">
        <span class="glyphicon glyphicon-shopping-cart"></span> Continue Shopping
    </a>
  </center><br><br>

 <br><br>
<%end%>

app/views/carts/_subcart.html.erb
    
    <div id="cart_list" class="cart-list">
        <div class="product">
            <%if @current_order.present? %>
                <% @current_order.line_items.each do |item| %>
                    <div class="cart-single-product">
                    <a class="product-image" href="#">
                        <img src="<%=item.product.images.first.avatar.url(:thumbnail) rescue ''%>" alt="">
                    </a>
                    <div class="product-details">
                        
                        <%= link_to cart_path(item), method: :delete, confirm: 'Delete?', class: 'remove', 'data-message' => 'Are you sure?', 'data-severity' => 'danger', :remote => true do %>
                        <i class="fa fa-times-circle"></i>
                        <%end%>

                        
                        <div class="product-name">
                            <span class="quantity-formated">
                                <span class="quantity"><span><%= item.quantity %></span></span>
                                X
                            </span>
                            <a href="/products/<%=item.product.id%>" class="cart-block-product-name" title="Faded Short Sleeves T-shirt"><%= item.get_name %></a>
                        </div>
                        <div class="product-atributes">
                            <a href="/products/<%=item.product.id%>" title="<%= item.get_name %>"> <%= item.get_name %></a>
                        </div>
                        <div class="prices">
                            <span class="price"> <%= show_price(item.total) %></span>
                        </div>
                    </div>                                                
                </div>
                <%end%>
          <%end%>                                           
        </div>
        <div class="cart-prices">
            <div class="cart-prices-line first-line"></div>
            <div class="cart-prices-line last-line">
                <span>Total &nbsp;</span>
                <span class="price pull-right">
                    <%if @current_order and  @current_order.line_items.present?%>
                        <%= show_price(@current_order.sub_total) %>
                        <%end%>
                            
                </span>
            </div>
        </div>
        <%if @current_order and @current_order.line_items.present?%>
        <p class="cart-buttons">
            <a class="btn btn-default button-small" href="/carts" title="Check out">
                <span>
                    Check out
                    <i class="fa fa-angle-right"></i>
                </span>
            </a>
        </p>
        <%end%>
    </div>  

app/views/carts/create.js.erb
$('#cart_products_count').html('<%=@current_order.line_items.count rescue '0'%>');
$("#subcart").html('<%=  j render(:partial => 'subcart', :object => @count) %>');

app/views/carts/destroy.js.erb
$("#subcart").html('<%=  j render(:partial => 'subcart', :object => @current_order) %>');
if ($("#main_cart")!= null){
	$("#main_cart").html('<%=  j render(:partial => 'cart_table', :object => @current_order) %>');
}

$('#cart_products_count').html('<%=@current_order.line_items.count rescue '0'%>')

app/views/carts/index.html.erb
<center>
   <br>
   <h1>SHOPPING CART</h1>
   <p>Customer Service Questions? +92 42 3 5241207-8</p>
</center>

<hr><br><br>
<div id="main_cart">
   <%= render 'cart_table' %>
</div> 

 
<br><br><br><br>